
import asyncio

import streamlit as st
from google import genai
from google.genai import types
from telegram import Bot

from prompts import (
    SUMMARY_REQUEST_PROMPT,
    SYSTEM_PROMPT,
    WELCOME_MESSAGE_TEMPLATE,
)



MODEL_NAME = "gemini-3.5-flash"

st.set_page_config(
    page_title="SnapStudy",
    page_icon="📚",
    layout="centered"
)




GEMINI_API_KEY = st.secrets["GEMINI_API_KEY"]
TELEGRAM_BOT_TOKEN = st.secrets["TELEGRAM_BOT_TOKEN"]




@st.cache_resource
def get_gemini_client():
    return genai.Client(api_key=GEMINI_API_KEY)


gemini_client = get_gemini_client()




def send_telegram(chat_id, user_name, summary):

    try:
        from telegram import Bot

        async def send_message():
            bot = Bot(token=TELEGRAM_BOT_TOKEN)

            await bot.send_message(
                chat_id=int(chat_id),
                text=f"""📚 SnapStudy Revision Summary

Hello {user_name}! 👋

{summary}

🎓 Keep learning. Keep improving!

🤖 Generated by SnapStudy AI"""
            )

        asyncio.run(send_message())

        return True, "Message sent successfully"

    except Exception as error:
        return False, str(error)

#def send_telegram(chat_id, user_name, summary):

    try:

        message_text = f"""📚 SnapStudy Revision Summary

Hello {user_name}! 👋

{summary}

🎓 Keep learning. Keep improving!

🤖 Generated by SnapStudy AI
"""

        async def send_message():

            bot = Bot(
                token=TELEGRAM_BOT_TOKEN
            )

            await bot.send_message(
                chat_id=chat_id,
                text=message_text
            )

        asyncio.run(send_message())

        return True, "Message sent successfully"

    except Exception as error:

        return False, str(error)#



def render_message(message):

    with st.chat_message(message["role"]):

        if message["kind"] == "text":

            st.write(
                message["content"]
            )

        elif message["kind"] == "image":

            st.image(
                message["content"]
            )


def add_message(role, kind, content):

    st.session_state.messages.append(
        {
            "role": role,
            "kind": kind,
            "content": content
        }
    )

    render_message(
        st.session_state.messages[-1]
    )




def ask_gemini(parts):

    try:

        return st.session_state.chat.send_message(
            parts
        ).text

    except Exception as error:

        return (
            f"Sorry, something went wrong: {error}"
        )



if "onboarded" not in st.session_state:

    st.title("📚 SnapStudy")

    st.caption(
        "Snap it. Learn it. Master it. 🎓"
    )

    with st.form("onboarding_form"):

        name = st.text_input(
            "Your name",
            placeholder="Enter your name"
        )

        telegram_chat_id = st.text_input(
            "Telegram Chat ID",
            placeholder="Example: 123456789",
            help=(
                "Start your Telegram bot before "
                "sending study summaries."
            )
        )

        submitted = st.form_submit_button(
            "Start Learning 🚀"
        )

    if submitted:

        if (
            not name.strip()
            or not telegram_chat_id.strip()
        ):

            st.warning(
                "Please fill in both your name "
                "and Telegram Chat ID."
            )

        else:

            st.session_state.name = (
                name.strip()
            )

            st.session_state.telegram_chat_id = (
                telegram_chat_id.strip()
            )

            # Create Gemini chat
            st.session_state.chat = (
                gemini_client.chats.create(
                    model=MODEL_NAME,
                    config=types.GenerateContentConfig(
                        system_instruction=SYSTEM_PROMPT
                    ),
                )
            )

            st.session_state.messages = []

            st.session_state.onboarded = True

            st.rerun()

    st.stop()




header_col, button_col = st.columns(
    [5, 2],
    vertical_alignment="center"
)


with header_col:

    st.title("📚 SnapStudy")


with button_col:

    send_disabled = (
        len(st.session_state.messages) <= 1
    )

    if st.button(
        "📤 Send Summary",
        disabled=send_disabled,
        use_container_width=True
    ):

        with st.spinner(
            "Preparing your revision summary..."
        ):

            summary = ask_gemini(
                [SUMMARY_REQUEST_PROMPT]
            )

        success, info = send_telegram(
            st.session_state.telegram_chat_id,
            st.session_state.name,
            summary
        )

        if success:

            st.success(
                "Study summary sent to Telegram! 📲"
            )

        else:

            st.error(
                f"Couldn't send the summary: {info}"
            )




st.caption(
    f"Logged in as {st.session_state.name} "
    "- study summaries go to Telegram"
)




if not st.session_state.messages:

    add_message(
        "assistant",
        "text",
        WELCOME_MESSAGE_TEMPLATE.format(
            name=st.session_state.name
        )
    )

else:

    for message in st.session_state.messages:

        render_message(message)




user_input = st.chat_input(
    "Ask a question or upload your study material 📚",
    accept_file=True,
    file_type=[
        "jpg",
        "jpeg",
        "png"
    ],
)




if user_input:

    photo = (
        user_input.files[0]
        if user_input.files
        else None
    )

    text = user_input.text

    parts = []



    if photo is not None:

        photo_bytes = photo.getvalue()

        add_message(
            "user",
            "image",
            photo_bytes
        )

        parts.append(
            types.Part.from_bytes(
                data=photo_bytes,
                mime_type=photo.type
            )
        )


  

    if text:

        add_message(
            "user",
            "text",
            text
        )

        parts.append(
            text
        )




    elif photo is not None:

        parts.append(
            """
            Analyze this study material.

            Identify the topic and explain it
            in simple language.

            Also provide:
            1. Important concepts
            2. Key points to remember
            3. Important definitions
            4. Examples if useful
            5. Possible exam questions
            """
        )



    with st.spinner(
        "📚 SnapStudy is studying your material..."
    ):

        answer = ask_gemini(
            parts
        )


    add_message(
        "assistant",
        "text",
        answer
    )

    st.rerun()
